const FreelancerLocation={
    
}
import { Contact } from "@/components/chatPage/chatTypes";
import { User, DollarSign, Phone, Mail, Facebook } from "lucide-react"
export const experienceData = [
    {
      id: 1,
      role: "Senior Software Engineer",
      company: "Google Inc.",
      dateWorked: "Jan 2020 - Present",
      description:
        "Developed scalable web applications and led a team of developers to build AI-powered solutions.",
    },
    {
      id: 2,
      role: "Frontend Developer",
      company: "Microsoft",
      dateWorked: "July 2018 - Dec 2019",
      description:
        "Designed and implemented UI components for Microsoft Teams, improving user engagement by 30%.",
    },
    {
      id: 3,
      role: "UI/UX Designer",
      company: "Adobe Systems",
      dateWorked: "May 2016 - June 2018",
      description:
        "Created user-friendly interfaces and improved Adobe XD’s design experience for millions of users.",
    },
  ];
  export const educationData = [
    {
      id: 1,
      degree: "Bachelor of Technology in Computer Science",
      institute: "Indian Institute of Technology (IIT) Delhi",
      dateOfStudy: "2019 - 2023",
      description: "Focused on software development, data structures, and artificial intelligence. Participated in multiple hackathons and research projects.",
    },
    {
      id: 2,
      degree: "Master of Business Administration (MBA)",
      institute: "Indian Institute of Management (IIM) Bangalore",
      dateOfStudy: "2023 - 2025",
      description: "Specializing in technology management and business strategy with a focus on startup ecosystems and digital transformation.",
    },
    {
      id: 3,
      degree: "High School Diploma",
      institute: "Delhi Public School, RK Puram",
      dateOfStudy: "2017 - 2019",
      description: "Completed studies in Science with a focus on Mathematics, Physics, and Computer Science. Secured top ranks in national-level competitive exams.",
    },
  ];
  
  export const verificationItems = [
    {
      icon: User,
      label: "Identity verified",
      status: "verify",
    },
    {
      icon: DollarSign,
      label: "Payment Verified",
      status: "verify",
    },
    {
      icon: Phone,
      label: "Phone Verified",
      status: "verify",
    },
    {
      icon: Mail,
      label: "Email Verified",
      status: "verify",
    },
    {
      icon: Facebook,
      label: "Facebook Verified",
      status: "verify",
    },
  ]
  export const skillsData = [
    {
      id: 1,
      name: "HTML",
      level: "Intermediate",
      percentage: 80,
    },
    {
      id: 2,
      name: "CSS",
      level: "Intermediate",
      percentage: 90,
    },
    {
      id: 3,
      name: "JavaScript",
      level: "Advanced",
      percentage: 95,
    },
  ]
  export  const users = [
    {
      id: 1,
      name: "Bhuvesh Singh",
      role: "UX designer, Gharphic designer",
      hourlyRate: 60,
      totalEarnings: 76,
      isOnline: true,
      rating: 4,
      reviews: 12,
      location: "Manhattan, USA",
      tags: ["Web design", "Web design", "Web design", "Web design"],
      badge: "Top rated",
    },
    {
      id: 2,
      name: "Malkhan Singh",
      role: "UX designer, Gharphic designer",
      hourlyRate: 60,
      totalEarnings: 76,
      isOnline: true,
      rating: 4,
      reviews: 12,
      location: "Manhattan, USA",
      tags: ["Web design", "Web design", "Web design", "Web design"],
      badge: "Top rated",
    },
    {
      id: 3,
      name: "Vibhuti Narayan Mishra",
      role: "UX designer, Gharphic designer",
      hourlyRate: 60,
      totalEarnings: 76,
      isOnline: true,
      rating: 4,
      reviews: 12,
      location: "Manhattan, USA",
      tags: ["Web design", "Web design", "Web design", "Web design"],
      badge: "Top rated",
    },
    // Add more users as needed
  ]
  export const jobs = [
    {
      id: 1,
      jobName: "Frontend Developer",
      description: "Looking for a skilled React developer to build UI components.",
      jobLevel: "Mid-Level",
      budget: 1500,
      rating: 4.5,
      postTime: "2 hours ago",
      reviews: 20,
      location: "Remote",
      badge: "Verified",
    },
    {
      id: 2,
      jobName: "Backend Engineer",
      description: "Seeking an experienced Node.js developer to work on APIs.",
      jobLevel: "Senior",
      budget: 2500,
      rating: 4.8,
      postTime: "1 day ago",
      reviews: 35,
      location: "New York, USA",
      badge: "Top Rated",
    },
    {
      id: 3,
      jobName: "UI/UX Designer",
      description: "Need a creative designer to revamp our mobile app UI.",
      jobLevel: "Junior",
      budget: 800,
      rating: 4.2,
      postTime: "5 hours ago",
      reviews: 15,
      location: "San Francisco, USA",
      badge: "Verified",
    },
    {
      id: 4,
      jobName: "Data Scientist",
      description: "Looking for a data scientist with experience in machine learning.",
      jobLevel: "Senior",
      budget: 3000,
      rating: 4.9,
      postTime: "3 days ago",
      reviews: 50,
      location: "Remote",
      badge: "Top Rated",
    },
    {
      id: 5,
      jobName: "DevOps Engineer",
      description: "Hiring a DevOps expert to streamline CI/CD pipelines.",
      jobLevel: "Mid-Level",
      budget: 2000,
      rating: 4.6,
      postTime: "6 hours ago",
      reviews: 25,
      location: "London, UK",
      badge: "Verified",
    },
    {
      id: 6,
      jobName: "DevOps Engineer",
      description: "Hiring a DevOps expert to streamline CI/CD pipelines.",
      jobLevel: "Mid-Level",
      budget: 2000,
      rating: 4.6,
      postTime: "6 hours ago",
      reviews: 25,
      location: "London, UK",
      badge: "Verified",
    },
  ];
  

 export const countries = [
    { value: "US", label: "United States" },
    { value: "GB", label: "United Kingdom" },
    { value: "FR", label: "France" },
    { value: "DE", label: "Germany" },
    { value: "JP", label: "Japan" },
    { value: "CN", label: "China" },
    { value: "IN", label: "India" },
    { value: "BR", label: "Brazil" },
    { value: "CA", label: "Canada" },
    { value: "AU", label: "Australia" },
    { value: "RU", label: "Russia" },
    { value: "IT", label: "Italy" },
    { value: "ES", label: "Spain" },
    { value: "MX", label: "Mexico" },
    { value: "KR", label: "South Korea" },
    { value: "NL", label: "Netherlands" },
    { value: "CH", label: "Switzerland" },
    { value: "SE", label: "Sweden" },
    { value: "NO", label: "Norway" },
    { value: "DK", label: "Denmark" },
    { value: "FI", label: "Finland" },
    { value: "NZ", label: "New Zealand" },
    { value: "ZA", label: "South Africa" },
    { value: "SG", label: "Singapore" },
    { value: "AE", label: "United Arab Emirates" },
    { value: "AR", label: "Argentina" },
    { value: "AT", label: "Austria" },
    { value: "BE", label: "Belgium" },
    { value: "CL", label: "Chile" },
    { value: "CO", label: "Colombia" },
    { value: "EG", label: "Egypt" },
    { value: "GR", label: "Greece" },
    { value: "HK", label: "Hong Kong" },
    { value: "HU", label: "Hungary" },
    { value: "ID", label: "Indonesia" },
    { value: "IE", label: "Ireland" },
    { value: "IL", label: "Israel" },
    { value: "MY", label: "Malaysia" },
    { value: "NG", label: "Nigeria" },
    { value: "PH", label: "Philippines" },
    { value: "PL", label: "Poland" },
    { value: "PT", label: "Portugal" },
    { value: "RO", label: "Romania" },
    { value: "SA", label: "Saudi Arabia" },
    { value: "TH", label: "Thailand" },
    { value: "TR", label: "Turkey" },
    { value: "UA", label: "Ukraine" },
    { value: "VN", label: "Vietnam" },
  ]

 export const contacts: Contact[] = [
    {
      id: "1",
      name: "Manmohan Desia",
      avatar: "/placeholder.svg?height=50&width=50",
      lastMessage: "You: Lets connect",
      time: "13m ago",
      isActive: true,
    },
    {
      id: "2",
      name: "Adam Smit",
      avatar: "/placeholder.svg?height=50&width=50",
      lastMessage: "Lets connect now i am free...",
      time: "13m ago",
      unread: 10,
    },
    {
      id: "3",
      name: "Kiran Kher",
      avatar: "/placeholder.svg?height=50&width=50",
      lastMessage: "You: Lets connect",
      time: "13m ago",
    },
    {
      id: "4",
      name: "Kabir khan",
      avatar: "/placeholder.svg?height=50&width=50",
      lastMessage: "You: Lets connect",
      time: "13m ago",
    },
    {
      id: "5",
      name: "Manmohan Desia",
      avatar: "/placeholder.svg?height=50&width=50",
      lastMessage: "You: Lets connect",
      time: "13m ago",
    },
    {
      id: "6",
      name: "Kajol Sharma",
      avatar: "/placeholder.svg?height=50&width=50",
      lastMessage: "You: Lets connect",
      time: "13m ago",
    },
  ]